import Foundation
import simd

/// ARKit (Y yukarı, metre) → Z yukarı yerel sistem (X, -Z, Y). LAS/PLY için ortak.
@inline(__always) func toZUp(_ p: SIMD3<Float>) -> SIMD3<Double> {
    SIMD3<Double>(Double(p.x), Double(-p.z), Double(p.y))
}

enum PLYWriter {
    /// Binary little-endian PLY: float x y z, uchar r g b
    static func write(_ cloud: PointCloud, to url: URL) throws {
        let header = """
        ply
        format binary_little_endian 1.0
        comment generated by LiDARScan, units: meters, Z-up
        element vertex \(cloud.count)
        property float x
        property float y
        property float z
        property uchar red
        property uchar green
        property uchar blue
        end_header

        """
        var data = Data(header.utf8)
        var body = [UInt8](repeating: 0, count: cloud.count * 15)
        body.withUnsafeMutableBytes { raw in
            var o = 0
            for i in 0..<cloud.count {
                let p = toZUp(cloud.positions[i])
                let f = [Float(p.x), Float(p.y), Float(p.z)]
                for v in f { raw.storeBytes(of: v.bitPattern.littleEndian, toByteOffset: o, as: UInt32.self); o += 4 }
                let c = cloud.colors[i]
                raw.storeBytes(of: c.x, toByteOffset: o, as: UInt8.self)
                raw.storeBytes(of: c.y, toByteOffset: o + 1, as: UInt8.self)
                raw.storeBytes(of: c.z, toByteOffset: o + 2, as: UInt8.self)
                o += 3
            }
        }
        data.append(contentsOf: body)
        try data.write(to: url, options: .atomic)
    }
}

enum LASWriter {
    /// LAS 1.2, nokta formatı 2 (XYZ + RGB), 26 bayt/nokta, ölçek 1 mm.
    static func write(_ cloud: PointCloud, to url: URL) throws {
        let n = cloud.count
        let pts = cloud.positions.map(toZUp)
        var mn = SIMD3<Double>(repeating: .infinity), mx = SIMD3<Double>(repeating: -.infinity)
        for p in pts { mn = simd_min(mn, p); mx = simd_max(mx, p) }
        if n == 0 { mn = .zero; mx = .zero }
        let scale = 0.001
        let offset = SIMD3<Double>(mn.x.rounded(), mn.y.rounded(), mn.z.rounded())

        var h = [UInt8](); h.reserveCapacity(227)
        func u8(_ v: UInt8) { h.append(v) }
        func u16(_ v: UInt16) { withUnsafeBytes(of: v.littleEndian) { h.append(contentsOf: $0) } }
        func u32(_ v: UInt32) { withUnsafeBytes(of: v.littleEndian) { h.append(contentsOf: $0) } }
        func f64(_ v: Double) { withUnsafeBytes(of: v.bitPattern.littleEndian) { h.append(contentsOf: $0) } }
        func fixed(_ s: String, _ len: Int) {
            var b = Array(s.utf8.prefix(len)); b += [UInt8](repeating: 0, count: len - b.count); h.append(contentsOf: b)
        }
        h.append(contentsOf: Array("LASF".utf8))
        u16(0); u16(0)                       // file source id, global encoding
        u32(0); u16(0); u16(0); h.append(contentsOf: [UInt8](repeating: 0, count: 8)) // GUID
        u8(1); u8(2)                         // sürüm 1.2
        fixed("iPhone LiDAR", 32)
        fixed("LiDARScan", 32)
        let cal = Calendar(identifier: .gregorian)
        let now = Date()
        u16(UInt16(cal.ordinality(of: .day, in: .year, for: now) ?? 1))
        u16(UInt16(cal.component(.year, from: now)))
        u16(227)                             // header boyutu
        u32(227)                             // nokta verisi ofseti
        u32(0)                               // VLR sayısı
        u8(2)                                // nokta formatı
        u16(26)                              // kayıt uzunluğu
        u32(UInt32(n))
        u32(UInt32(n)); for _ in 0..<4 { u32(0) }   // return başına sayı
        f64(scale); f64(scale); f64(scale)
        f64(offset.x); f64(offset.y); f64(offset.z)
        f64(mx.x); f64(mn.x); f64(mx.y); f64(mn.y); f64(mx.z); f64(mn.z)
        precondition(h.count == 227)

        var body = [UInt8](repeating: 0, count: n * 26)
        body.withUnsafeMutableBytes { raw in
            var o = 0
            for i in 0..<n {
                let p = pts[i]
                let xi = Int32(((p.x - offset.x) / scale).rounded())
                let yi = Int32(((p.y - offset.y) / scale).rounded())
                let zi = Int32(((p.z - offset.z) / scale).rounded())
                raw.storeBytes(of: xi.littleEndian, toByteOffset: o, as: Int32.self)
                raw.storeBytes(of: yi.littleEndian, toByteOffset: o + 4, as: Int32.self)
                raw.storeBytes(of: zi.littleEndian, toByteOffset: o + 8, as: Int32.self)
                // 12: intensity(u16)=0, 14: flags (return 1 of 1), 15: class, 16: scan angle, 17: user data, 18: point source id
                raw.storeBytes(of: 0x09, toByteOffset: o + 14, as: UInt8.self)   // return number=1, number of returns=1
                let c = cloud.colors[i]
                raw.storeBytes(of: (UInt16(c.x) * 257).littleEndian, toByteOffset: o + 20, as: UInt16.self)
                raw.storeBytes(of: (UInt16(c.y) * 257).littleEndian, toByteOffset: o + 22, as: UInt16.self)
                raw.storeBytes(of: (UInt16(c.z) * 257).littleEndian, toByteOffset: o + 24, as: UInt16.self)
                o += 26
            }
        }
        var data = Data(h); data.append(contentsOf: body)
        try data.write(to: url, options: .atomic)
    }
}
